### ISSUE TITLE
Improve Cart Interaction: Indicating Product in Cart and Quick Navigation to Cart

### ISSUE THREAD

**Issue by dhuruvandb** [RishiBakshii/mern-ecommerce#13]
**Description:**

This Feature addresses two improvements to the shopping cart interaction:

    -     Product Addition Feedback: Currently, when a user clicks the "Add to Cart" button, it disappears, which can confuse the user about whether the product was added to the cart. To enhance clarity, the "Add to Cart" button should be replaced with a text saying "Added to Cart" once the product is successfully added. This will provide a clearer visual cue that the product is in the cart.
    
    -     Quick Cart Navigation: On the individual product page, there is a button near the quantity selector that indicates the product is in the cart. However, if the user wants to go to the cart, they must navigate to the top right corner and click on the cart icon. Instead, the cart button should be made clickable, allowing users to directly navigate to the cart page from the product page. This will simplify the user experience and improve navigation.

**Expected Outcome:**

    When a product is added to the cart, the "Add to Cart" button should change to "Added to Cart."
    The cart button on the product page should be clickable, allowing users to directly navigate to the cart.
    
1) For Add to cart button issue
    
Before:

on clicking the Add to Cart button

![image](https://github.com/user-attachments/assets/0dfed93a-6721-40b2-8efd-61a95efb92f6)

After:

on clicking the Add to Cart button

![image](https://github.com/user-attachments/assets/2abe5fa5-bc5a-46ae-b399-0d0998bae444)

@RishiBakshii Please provide your suggestions.

**Comment by RishiBakshii** [comment]
hi @dhuruvandb i guess both the things that you mentioned 
1) after adding the product in cart, the button should not disappear instead it should show "Added to cart"
2) In the Product Page the button that shows "In-cart" should also be clickable and take the user to cart instead of going to the top right corner to click the cart button

These are really good changes and i really really appreciate you for checking out this project and raising this feature issue here

And also the issues you have mentioned shows that you have truly spent some good time navigating the project

Summary:
I really like the proposed features, if you want to open source contribute let me know i will assign this feature to you :)

Thanks @dhuruvandb

**Comment by dhuruvandb** [comment]
Yes please @RishiBakshii

**Comment by RishiBakshii** [comment]
i have assigned the issue to you @dhuruvandb all the best

**Comment by dhuruvandb** [comment]
@RishiBakshii  Thank you! I have already made the changes and submitted a pull request. It would be great if you could review it and provide any suggestions or feedback.

**Comment by RishiBakshii** [comment]
@dhuruvandb i have reviewed it and everything looks good, so yeah your pull request is merged. Great Work and thankyou so much for your open source contribution ❤️

**Comment by dhuruvandb** [comment]
@RishiBakshii  You are most welcome. I have many ideas i will implement one by one in upcoming days.

Happy coding!
